---
- name: Report Kernel version
  hosts: all
  become: true
  gather_facts: true

  tasks: 
    - name: Fill whit hostvars
      template:
        src:  report.j2
        dest: kernel-release-report.txt
      delegate_to: localhost
