---
- name: Report Kernel version
  hosts: all
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Print facts
      debug:
        msg: The server name is
        "{{ ansible_hostname }}"
        Kernel version "{{ ansible_kernel }}"
        Distribution "{{ ansible_distribution }}" "{{ ansible_distribution_version }}"
