---
- name: Report Kernel version
  hosts: all
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Print facts
      debug:
        msg: The server name is
        {{ hostvars[host].ansible_hostname }}
        Kernel version {{ hostvars[host].ansible_kernel }}
        Distribution {{ hostvars[host].ansible_distribution }} {{ hostvars[host].ansible_distribution_version }}
