---
- name: Report Kernel version
  hosts: all
  connection: local
  become: true
  gather_facts: true

  tasks:
    - name: Fill whit var jinja2
      template:
        src:  report.j2
        dest: kernel-release-report.txt
#      delegate_to: localhost
