---
- name: Report Kernel version
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Print facts
      debug:
        msg:
         - "The server name is {{ ansible_hostname }}"
    - debug:
        msg:
         - "Kernel version {{ ansible_kernel }}"
    - debug:
        msg:
         - "Distribution {{ ansible_distribution }} : {{ ansible_distribution_version }}"
