---
- name: Create user "{{ user }}"
  hosts: all
  gather_facts: true

  tasks:

    - name: Add the user "{{ user }}" with uid and primary group
      user:
        name: "{{ user }}"
        comment: John Wick
        group: "{{ group }}"
        uid: 1040
