---
- name: Hardening whit SELINUX
  hosts: all
  become: true
  gather_facts: no

  tasks:

  - name: State of SELINUX en enforcing
    selinux:
      policy: targeted
      state: enforcing

  - name: Nmap is removed on all servers Linux
    package:
      name: nmap
      state: absent

  - name: uninstall gcc through package to all linux
    package:
      name: gcc
      state: absent
