---
- name: Start service for apache & firewalld
  hosts: all

  tasks:

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: firewalld enabled and running
    service:
      name: firewalld
      enabled: true
      state: started

  - name: firewalld permits http service
    firewalld:
      service: http
      permanent: true
      state: enabled
      immediate: yes
