---
- name: Latest Apache version installed
  hosts: all
  gather_facts: true

  tasks:


  - name: latest firewalld version installed
    yum:
      name: firewalld
      state: latest

  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: Ensure proper Apache configuration
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf


  - name: Deploy index.html from template
    template:
      src: "{{ stage }}_index.html.j2"
      dest: /var/www/html/index.html
